# Generated by Django 4.2.4 on 2023-08-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tdate',
            field=models.DateField(default='1993-11-04'),
            preserve_default=False,
        ),
    ]
